keys:
  - &squamigera-admin age1zhh4jqkn8cqyjekwu0ptxsuvqcahlhy74zfy8d7dy9zzckzj5utse96hf3
  - &nois-ark age1d7zl8mnr7v8rdqprchh8vg2vchr4xs4r5yqpwp6jca2c7m3sefuqxumxwz
  - &radiata-rkv12 age1fnw4cysrggsjd36m85a89pyjmkwjf7ey52fsmya5ghqzzhu3vg0qwe3ay4
  - &albiflora age1m869k2r20z7487gc3adxhqdnmv3y9m9u6xkh5jffskxmcvrgrdjqkn3s6v
  - &albiflora-w963n age1y67vyxzll5wgckz533j6u8lwjcjzdzsrdwnwmndpwvm5ez6fyg3qax5vr0

creation_rules:
  - path_regex: modules/searxng/secrets/.*
    key_groups:
      - age: [ *nois-ark, *squamigera-admin ]
  - path_regex: modules/calendar/secrets/.*
    key_groups:
      - age: [ *radiata-rkv12, *albiflora-w963n, *squamigera-admin ]
  - path_regex: modules/hosts/albiflora/secrets/.*
    key_groups:
      - age: [ *albiflora, *squamigera-admin ]
