{
  # Google Calendar sync (vdirsyncer) + TUI client (khal). OAuth secrets are
  # sops-encrypted in ./secrets/calendar.yaml (age key: ~/.config/sops/age/
  # keys.txt, generated by base/secret/age.nix) and decrypted into the user
  # runtime dir by the sops-nix home-manager module.
  flake.modules.homeManager.calendar =
    { inputs, config, ... }:
    {
      imports = [
        inputs.sops-nix.homeManagerModules.sops
      ];

      sops = {
        age.keyFile = "${config.home.homeDirectory}/.config/sops/age/keys.txt";

        secrets = {
          "oauth_client_id".sopsFile = ./secrets/calendar.yaml;
          "oauth_client_secret".sopsFile = ./secrets/calendar.yaml;
        };
      };

      accounts.calendar = {
        basePath = ".calendar";
        accounts.main = {
          name = "main";
          remote = {
            type = "google_calendar";
          };
          khal = {
            enable = true;
            addresses = [
              "r.k.v.1225kaito@gmail.com"
            ];
            type = "discover";
          };
          vdirsyncer = {
            enable = true;
            clientIdCommand = [
              "cat"
              config.sops.secrets."oauth_client_id".path
            ];
            clientSecretCommand = [
              "cat"
              config.sops.secrets."oauth_client_secret".path
            ];
            tokenFile = "${config.xdg.dataHome}/vdirsyncer/google-calendar-token";
            collections = [
              "from a"
              "from b"
            ];
            metadata = [
              "color"
              "displayname"
            ];
          };
        };
      };

      programs.khal = {
        enable = true;
        locale = {
          timeformat = "%H:%M";
          dateformat = "%Y-%m-%d";
          longdateformat = "%Y-%m-%d";
          datetimeformat = "%Y-%m-%d %H:%M";
          longdatetimeformat = "%Y-%m-%d %H:%M";
        };
      };

      programs.vdirsyncer = {
        enable = true;
      };

      services.vdirsyncer = {
        enable = true;
      };
    };
}
